"""2 map

Revision ID: 2a97891541ca
Revises: 404aa57e647f
Create Date: 2019-01-17 16:02:41.082240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a97891541ca'
down_revision = '404aa57e647f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('manadger', sa.String(length=250), nullable=True))
    op.add_column('invoice', sa.Column('route_date', sa.String(length=10), nullable=True))
    op.add_column('route', sa.Column('google_distance', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('google_polyline', sa.PickleType(), nullable=True))
    op.add_column('route', sa.Column('google_popup', sa.Text(), nullable=True))
    op.add_column('route', sa.Column('google_waypoint_order', sa.PickleType(), nullable=True))
    op.add_column('route', sa.Column('manadger_distance', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('manadger_polyline', sa.PickleType(), nullable=True))
    op.add_column('route', sa.Column('manadger_popup', sa.Text(), nullable=True))
    op.add_column('route', sa.Column('manadger_waypoint_order', sa.PickleType(), nullable=True))
    op.add_column('route', sa.Column('points', sa.PickleType(), nullable=True))
    op.add_column('route', sa.Column('volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'volume')
    op.drop_column('route', 'points')
    op.drop_column('route', 'manadger_waypoint_order')
    op.drop_column('route', 'manadger_popup')
    op.drop_column('route', 'manadger_polyline')
    op.drop_column('route', 'manadger_distance')
    op.drop_column('route', 'google_waypoint_order')
    op.drop_column('route', 'google_popup')
    op.drop_column('route', 'google_polyline')
    op.drop_column('route', 'google_distance')
    op.drop_column('invoice', 'route_date')
    op.drop_column('invoice', 'manadger')
    # ### end Alembic commands ###
