"""add Route and Invoice

Revision ID: 2e1706e0c022
Revises: 87a6e297a144
Create Date: 2018-12-25 23:28:03.897739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1706e0c022'
down_revision = '87a6e297a144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('route')
    # ### end Alembic commands ###
