"""1 init database

Revision ID: 404aa57e647f
Revises: 
Create Date: 2019-01-07 23:46:01.369754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404aa57e647f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('car', sa.String(length=50), nullable=True),
    sa.Column('car_volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('client_nickname', sa.String(length=32), nullable=True),
    sa.Column('client_name', sa.String(length=250), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('city_lon', sa.Float(), nullable=True),
    sa.Column('city_lat', sa.Float(), nullable=True),
    sa.Column('route_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('route')
    # ### end Alembic commands ###
