"""1 init

Revision ID: 764e0fb7b3a0
Revises: 
Create Date: 2019-01-18 17:27:44.293876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764e0fb7b3a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('route_datetime', sa.DateTime(), nullable=True),
    sa.Column('car', sa.Unicode(length=50), nullable=True),
    sa.Column('car_volume', sa.Float(), nullable=True),
    sa.Column('car_volume_opt', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('points', sa.PickleType(), nullable=True),
    sa.Column('manadger_waypoint_order', sa.PickleType(), nullable=True),
    sa.Column('manadger_polyline', sa.PickleType(), nullable=True),
    sa.Column('manadger_popup', sa.Text(), nullable=True),
    sa.Column('manadger_distance', sa.Float(), nullable=True),
    sa.Column('google_waypoint_order', sa.PickleType(), nullable=True),
    sa.Column('google_polyline', sa.PickleType(), nullable=True),
    sa.Column('google_popup', sa.Text(), nullable=True),
    sa.Column('google_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('manadger', sa.Unicode(length=250), nullable=True),
    sa.Column('invoice_datetime', sa.DateTime(), nullable=True),
    sa.Column('route_datetime', sa.DateTime(), nullable=True),
    sa.Column('client_nickname', sa.Unicode(length=32), nullable=True),
    sa.Column('client_name', sa.Unicode(length=250), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('city', sa.Unicode(length=40), nullable=True),
    sa.Column('city_lon', sa.Float(), nullable=True),
    sa.Column('city_lat', sa.Float(), nullable=True),
    sa.Column('route_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('route')
    # ### end Alembic commands ###
